print("app started, throwing exception")
raise Exception("stuff")